//! Campaign XIII — public receipts. Turn a Colosseum report into the
//! markdown the whole world is allowed to read (Law VII).

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct ReportFile {
    pub report: SuiteReportLite,
    #[serde(default)]
    pub provider: String,
    #[serde(default)]
    pub model: String,
}

#[derive(Debug, Deserialize)]
pub struct SuiteReportLite {
    pub suite_name: String,
    pub pass_at_k: f64,
    pub total_cost_cents: u64,
    pub cases: Vec<CaseLite>,
}

#[derive(Debug, Deserialize)]
pub struct CaseLite {
    pub case_id: String,
    pub passed_at_k: bool,
    #[serde(default)]
    pub trial_flags: Vec<bool>,
}

/// Render receipts.md section for one report.
pub fn render(reports: &[ReportFile], bellona_version: &str) -> String {
    let mut out = String::from("# Bellona — Public Receipts\n\n");
    out.push_str("> Harness-controlled numbers only. Every row cites harness, ");
    out.push_str("provider/model, and date. `pass^k` = probability ALL k repeats succeed.\n\n");
    out.push_str("| Suite | Provider/Model | Cases | pass^k | Cost (¢) | Verdict |\n");
    out.push_str("|-------|----------------|-------|--------|----------|---------|\n");

    for r in reports {
        let cases = r.report.cases.len();
        let passed = r.report.cases.iter().filter(|c| c.passed_at_k).count();
        let verdict = if r.report.pass_at_k >= 0.99 {
            "✅"
        } else if r.report.pass_at_k >= 0.8 {
            "⚠️"
        } else {
            "❌"
        };
        out.push_str(&format!(
            "| {} | {}/{} | {}/{} | {:.3} | {} | {} |\n",
            r.report.suite_name,
            r.provider,
            r.model,
            passed,
            cases,
            r.report.pass_at_k,
            r.report.total_cost_cents,
            verdict
        ));
    }

    out.push_str(&format!(
        "\n_Generated by bellona v{bellona_version}. Offline suites use the \
         deterministic EchoModel: they prove the plumbing, not model quality._\n"
    ));
    out
}
